version: '3'

services:
    api:
        image: ostwilkens/strapi:latest
        network_mode: bridge
        # build:
        #     context: ./api
        #     dockerfile: Dockerfile
        volumes:
            - ./api:/srv/app
            - /srv/app/node_modules/
            - /srv/app/.cache/
        command: bash -c "yarn && strapi develop"
        environment:
            VIRTUAL_HOST: ful-api.dev.kodkvarnen.se
    gen:
        image: ostwilkens/gridsome:latest
        network_mode: bridge
        links:
            - api
        # build:
        #     context: ./gen
        #     dockerfile: Dockerfile
        restart: on-failure
        volumes:
            - ./gen:/srv/app
            - /srv/app/node_modules/
        command: bash -c "yarn && gridsome develop"
        environment:
            VIRTUAL_HOST: ful-gen.dev.kodkvarnen.se